---

- name: Collect list of available agents on the Checkmk server
  delegate_to: "{{ checkmk_server_url }}"
  ansible.builtin.command: |
     ls /opt/omd/sites/{{ checkmk_site_name }}/share/check_mk/agents/
  run_once: true
  register: agents_result

- name: Filter the *_all.deb agent
  ansible.builtin.set_fact:
    checkmk_deb_agent : "{{ item }}"
  loop: "{{ agents_result.stdout_lines }}"
  when: item.endswith('_all.deb')
  run_once: true

- name: Download CheckMK agent onto the server
  ansible.builtin.get_url:
    url: "https://{{ checkmk_server_url }}/{{ checkmk_site_name }}/check_mk/agents/{{ checkmk_deb_agent }}"
    dest: "/tmp/{{ checkmk_deb_agent }}"
    validate_certs: no

- name: Add Checkmk agent package and prerequisites
  ansible.builtin.apt:
    deb: /tmp/{{ checkmk_deb_agent }}

- name: "Create host on CheckMK server."
  delegate_to: localhost
  become: false
  tribe29.checkmk.host:
    server_url: "https://{{ checkmk_server_url }}/"
    site: "{{ checkmk_site_name }}"
    automation_user: "automation"
    automation_secret: "{{ checkmk_automation_secret }}"
    folder: "{{ checkmk_agent_folder | default(omit) }}"
    host_name: "{{ inventory_hostname }}"
    #attributes: "{{ checkmk_agent_host_attributes }}"
    state: "present"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
  register: checkmk_agent_create_result
  failed_when: |
    (checkmk_agent_create_result.failed == true) and
    ("The host is already part of the specified target folder" not in checkmk_agent_create_result.msg)

- name: Print checkmk_agent_create_result variable
  debug:
    var: checkmk_agent_create_result

- name: "Add newly discovered services on host."
  delegate_to: localhost
  become: no
  tribe29.checkmk.discovery:
    server_url: "https://{{ checkmk_server_url }}/"
    site: "{{ checkmk_site_name }}"
    automation_user: "automation"
    automation_secret: "{{ checkmk_automation_secret }}"
    host_name: "{{ inventory_hostname }}"
    state: "refresh"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"

# Enabling checks should be done manually after discovery!

# - name: "Activate changes on all sites including foreign changes"
#   delegate_to: localhost
#   become: no
#   tribe29.checkmk.activation:
#     server_url: "https://{{ checkmk_server_url }}/"
#     site: "{{ checkmk_site_name }}"
#     automation_user: "automation"
#     automation_secret: "{{ checkmk_automation_secret }}"
#     force_foreign_changes: true
#     validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
#   run_once: true